### ISSUE TITLE
Transition to 'Harvest' / 'Dead' Stage After Episode Termination

### ISSUE THREAD

**Issue by thexabd** [farm-gym/farm-gym#11]
The plant stage observation does not change to 11 when the plant is harvested or 12 when the plant is dead, after episode termination

**Comment by thexabd** [comment]
The plant stage observation does not change to 11 when the plant is harvested or 12 when the plant is dead, after episode termination

**Comment by brahimdriss** [comment]
Thank you for raising this issue.
Fixed in [ee9a988](https://github.com/farm-gym/farm-gym/commit/ee9a988130fcf300257eb445335646c5f155a293)
